#!/bin/bash
clear
printf "\e[1;36m\e[1;3m  Throw bilgi alma ekranı  \e[0m\e[0m\n\n"
printf "\e[1;94m ---------------------------------- \e[0m\n"
printf "\e[1;91m ● \e[0m\e[1;95m Ağdan Bir Sunucuyu Çıkarma \e[0m\n"
printf "\e[1;94m ---------------------------------- \e[0m\n\n"
printf "\e[1;1m Seçili adrese ARP Spoof saldırısı düzenleyerek cihazın ağdan düşmesini sağlar.\e[0m\n\n" 
printf "\e[1;94m ---------------------------------- \e[0m\n"
printf "\e[1;91m ● \e[0m\e[1;95m Ağdan Seçili Sunucuları Çıkarma \e[0m\n"
printf "\e[1;94m ---------------------------------- \e[0m\n\n"
printf "\e[1;1m Seçili adreslere ARP Spoof saldırısı düzenleyerek cihazın ağdan düşmesini sağlar.\e[0m\n\n" 
printf "\e[1;94m ---------------------------------- \e[0m\n"
printf "\e[1;91m ● \e[0m\e[1;95m Ağdan Tüm Sunucuları Çıkarma \e[0m\n"
printf "\e[1;94m ---------------------------------- \e[0m\n\n"
printf "\e[1;1m Ağ cihazına aircrack-ng aracının altyapısını kullanarak saldırı yapar.\e[0m\n\n" 
printf "\e[1;94m ---------------------------------- \e[0m\n"
printf "\e[1;91m ● \e[0m\e[1;95m Bilgi \e[0m\n"
printf "\e[1;94m ---------------------------------- \e[0m\n\n"
printf "\e[1;1m Bu araç Ağ Programlama dersi proje ödevidir. Geliştiriciler herhangi bir zarardan sorumlu değillerdir.\e[0m\n\n" 
